import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import BarChart from "./components/BarChart";
import Accordion from "./components/Accordion";
import SocialsFooter from "./components/SocialFooter";

const Home: NextPage = () => {
  const dataset = api.example.mock.useQuery({ text: "from tRPC" });
  return (
    <>
      <Head>
        <title>Censorship Oracle</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-bold tracking-tight">
            Censorship Oracle
          </h1>
          <div className="text-2xl text-center w-3/4">
            <p>Ethereum is censorship resistant . . . r-right?</p>
          </div>
          <div className="text-xl text-center w-3/4">
            <p>Lick other cats</p>
          </div>
          
  
          <p className="text-xl text-white">
            {dataset.data ? dataset.data.data.length : "Loading tRPC query..."}
          </p>

          <div className="w-full flex justify-center">
            <div>Missing Blocks Percentage</div>
          </div>

          <div className="w-full flex justify-center">
            <BarChart/>
          </div>

        


          <div className="container mx-auto px-4 py-8">
            <Accordion title="How can blocks go missing?">
              <p>There are different types of censorship</p>
            </Accordion>
            <Accordion title="How does censorship affect distributed networks?">
              <p>Content for Section 2.</p>
            </Accordion>
            <Accordion title="What's the purpose of a censorship oracle?">
              <p>Content for Section 2.</p>
            </Accordion>
          </div>

          <SocialsFooter/>
          

        </div>
      </main>
    </>
  );
};

export default Home;
