import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import BarChart from "./components/BarChart";
import Accordion from "./components/Accordion";
import SocialsFooter from "./components/SocialFooter";

const Home: NextPage = () => {
  const dataset_eth = api.example.getSubgraphData.useQuery({ chainid: 1, daySize: 30, monthSize: 36, orderByProperty: 'blockNumberHigh', orderDirection: 'desc' });
  const dataset_gnosis = api.example.getSubgraphData.useQuery({ chainid: 100 , daySize: 30, monthSize: 36, orderByProperty: 'blockNumberHigh', orderDirection: 'desc' });
  return (
    <>
      <Head>
        <title>Ethereumverse - Missing Blocks</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-bold tracking-tight">
          Ethereumverse - Missing Blocks
          </h1>
          <div className="text-2xl text-center w-3/4">
            <p>All History</p>
          </div>
          <div className="w-full flex justify-center">
          {dataset_eth.data && dataset_gnosis.data
              ? <BarChart isDay={false} dataset_eth={dataset_eth.data} dataset_gnosis={dataset_gnosis.data}/>
              : "Chart Loading..."
            }
          </div>
          <div className="text-2xl text-center w-3/4">
            <p>30 Days</p>
          </div>
          <div className="w-full flex justify-center">
          {dataset_eth.data && dataset_gnosis.data
              ? <BarChart  isDay={true} dataset_eth={dataset_eth.data} dataset_gnosis={dataset_gnosis.data}/>
              : "Chart Loading..."
            }
          </div>
          <div className="container mx-auto px-4 py-8">
            <Accordion title="How can blocks go missing?">
              <p>On Ethereum and Gnosis chain, blocks are produced like clockwork. Every 12 seconds (5 on Gnosis), a block can be produced. <br></br><br></br>
                However if validators are offline, blocks may go missing.
<br></br><br></br>There may also be sophisticated network level <a className="underline text-blue-500" href="https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/attack-and-defense/#reorgs" rel="noreferrer">
  attacks</a> such as eclipse attacks which fork out proposed blocks, resulting in block reorganizations.</p>
            </Accordion>
          </div>

          <SocialsFooter/>
          

        </div>
      </main>
    </>
  );
};

export default Home;
