import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import BarChart from "./components/BarChart";
import Accordion from "./components/Accordion";
import SocialsFooter from "./components/SocialFooter";

const Home: NextPage = () => {
  const dataset = api.example.mock.useQuery({ text: "from tRPC" });
  return (
    <>
      <Head>
        <title>Censorship Oracle</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-bold tracking-tight">
            Censorship Oracle
          </h1>
          <div className="text-2xl text-center w-3/4">
            <p>Ethereum is censorship resistant . . . r-right?</p>
          </div>
  
          <p className="text-xl text-white">
            {dataset.data ? dataset.data.data.length : "Loading tRPC query..."}
          </p>

          <div className="w-full flex justify-center">
            <div>% Missing Blocks</div>
          </div>

          <div className="w-full flex justify-center">
            <BarChart/>
          </div>

        


          <div className="container mx-auto px-4 py-8">
            <Accordion title="How can blocks go missing?">
              <p>On Ethereum and Gnosis chain, blocks are produced like clockwork. Every 12 seconds (5 on Gnosis), a block can be produced.
                However if validators are offline, blocks may go missing.
<br></br>There may also be sophisticated network level <a className="underline text-blue-500" href="https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/attack-and-defense/#reorgs" rel="noreferrer">
  attacks</a> such as eclipse attacks which fork out proposed blocks, resulting in block reorganizations.</p>
            </Accordion>
            <Accordion title="How does censorship affect rollups and dapps?">
              <p>Optimistic rollups such as Arbitrum or Optimism depend on honest actors challenging false claims. If the honest actors are censored, then the rollup or dapp fails.</p>
            </Accordion>
            <Accordion title="What's the purpose of a censorship oracle?">
              <p>To avoid censorship, optimistic rollups use a 7 day challenge period. This means any messages or withdrawals from the rollup incurs a latency of 7 days.

With a censorship oracle we can speed up the challenge window to hours instead of days</p>
            </Accordion>
            <Accordion title="How does the censorship oracle work?">
              <p>
              The censorship oracle is based on a ethereum research forum <a className="underline text-blue-500" href="https://ethresear.ch/t/reducing-challenge-times-in-rollups/14997" rel="noreferrer">
  post</a> by Ed Felten.
<br></br>
The idea is that there is enough information on-chain to determine statistically whether forking censorship occured.
<br></br>
For example, if we assume 10% of validators do not censor transactions, and if fewer than 4 blocks are missing over a 2 hour time period, then we know the risk of censorship is 1 in a million chance.
              </p>
            </Accordion>
          </div>

          <SocialsFooter/>
          

        </div>
      </main>
    </>
  );
};

export default Home;
